[app]
service_id = 1

[service]
address = "tcp://0.0.0.0:8171"
data_error_continue = true

[discovery]
name = "event"
id = "bus"
address = "tcp://127.0.0.1:8171"
endpoints = ["{\"address\":\"http://127.0.0.1:6500\",\"datacenter\":\"dev\"}"]
ttl = "30s"
